language: php

env:
  global:
    - CC_TEST_REPORTER_ID=ebd3d4f20e92c8e07a468bd39bfbe0ecf8e1a2e5fd178a5e880c77e16f14c3ed

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - hhvm

install:
  - composer install

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - vendor/bin/phpunit --coverage-clover=clover.xml

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

matrix:
  allow_failures:
    - php: hhvm

fast_finish: true

sudo: false
